export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';

export const CREATE_BOOKS_REQUEST = 'CREATE_BOOKS_REQUEST';
export const CREATE_BOOKS_SUCCESS = 'CREATE_BOOKS_SUCCESS';
export const CREATE_BOOKS_FAILURE = 'CREATE_BOOKS_FAILURE';

export const UPDATE_BOOKS_REQUEST = 'UPDATE_BOOKS_REQUEST';
export const UPDATE_BOOKS_SUCCESS = 'UPDATE_BOOKS_SUCCESS';
export const UPDATE_BOOKS_FAILURE = 'UPDATE_BOOKS_FAILURE';

export const DELETE_BOOKS_REQUEST = 'DELETE_BOOKS_REQUEST';
export const DELETE_BOOKS_SUCCESS = 'DELETE_BOOKS_SUCCESS';
export const DELETE_BOOKS_FAILURE = 'DELETE_BOOKS_FAILURE';
